language: perl

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

os: osx
## only 7.3 https://github.com/travis-ci/perl-builder/blob/a688863174e61974816e334eff885953ddb4a1c8/.travis.yml#L26-L29
osx_image: xcode7.3

before_install:
 - |
   if [[ ! -x $HOME/perl5/perlbrew/bin/perlbrew ]]; then
     \curl -L https://install.perlbrew.pl | bash
     source $HOME/perl5/perlbrew/etc/bashrc
     perlbrew --quiet install-cpanm
     perlbrew use $TRAVIS_PERL_VERSION
   fi 

script:
  - true
